### ISSUE TITLE
Documentation on how to run `Babel`

### ISSUE THREAD

**Issue by cartal** [wukevin/babel#1]
Hi

This work looks very interesting. I have started to play around with the code, but I'm not entirely sure I'm doing it correctly.

Are there plans to add some documentation for the tool with more concise examples? Can the tool work directly on `anndata` objects? 

Do you have a more detail example that you could share? 

Thank you!

**Comment by wukevin** [comment]
Since early December, we've added more documentation on how to run the tool, as well as an example for how to run BABEL and do a quick analysis of its results here: https://github.com/wukevin/babel/blob/main/jupyter/pbmc_imputed_rna_eval_clean.ipynb

Regarding `anndata` objects: yes, the tool can work directly on them. However, there's quite a few steps (not just preprocessing, but also format-wise) that go into making an AnnData object compatible with the data loaders and such for the model. Instead of working directly with AnnData objects, I recommend saving the AnnData object as a `.h5ad` file and using BABEL's command-line interface to run it (see the link above).

Let me know if you have any other questions, or if there are any particular functionalities you'd like to see.
